FROM prom/prometheus:latest
COPY prometheus.yml /etc/prometheus/prometheus.yml
ENTRYPOINT ["/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.listen-address=0.0.0.0:9090"]