app = "b01-prometheus"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile.prometheus"  # Use this instead of 'image'
  # Remove or comment out the image line
  # image = "prom/prometheus:latest"

[env]
  TZ = "UTC"

[mounts]
  source = "prometheus_data"
  destination = "/prometheus"

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512