global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # This works in a deployed container
      
  - job_name: 'supplier-service-koyeb'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: 'https'
    static_configs:
      - targets: ['adverse-anetta-b01-84d81d85.koyeb.app']
        labels:
          application: 'supplier-service'
          namespace: 'koyeb'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'product-service-koyeb'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: 'https'  # Changed to HTTPS since it's on Koyeb
    static_configs:
      - targets: ['invisible-shay-sopigoo-b06fd14f.koyeb.app']
        labels:
          application: 'product-service-koyeb'
          namespace: 'amazon'
    tls_config:
      insecure_skip_verify: true
      
  - job_name: 'pelanggan-service-koyeb'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: 'https'  # Changed to HTTPS since it's on Koyeb
    static_configs:
      - targets: ['standard-kirby-manajemen-pelanggan-08f7f84c.koyeb.app']
        labels:
          application: 'pelanggan-service'
          namespace: 'koyeb'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'auth-service-koyeb'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: 'https'  # Changed to HTTPS since it's on Koyeb
    static_configs:
      - targets: ['regulatory-jacki-b01authentication-9cd1d462.koyeb.app']
        labels:
          application: 'auth-service'
          namespace: 'koyeb'
    tls_config:
      insecure_skip_verify: true