apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://b01-prometheus.fly.dev
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true